/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-06-04 09:33:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jsp.expensetracker.entity.Expense;
import com.jsp.expensetracker.entity.User;
import com.jsp.expensetracker.service.*;
import java.util.*;

public final class CategoryGraph_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.jsp.expensetracker.service");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.Expense");
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("                \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Category Graph</title>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/c51795afff.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"tablestyle.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"media/expenses-removebg-preview (1).png\">\r\n");
      out.write("    <style>\r\n");
      out.write("      body\r\n");
      out.write("        {\r\n");
      out.write("            background-image: url(media/bg.png);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-size:cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		*\r\n");
      out.write("        {\r\n");
      out.write("            margin:0%;\r\n");
      out.write("            padding:0%;\r\n");
      out.write("        }\r\n");
      out.write("        .header\r\n");
      out.write("        {\r\n");
      out.write("            margin:0px;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            height:90px;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background-color: rgba(153, 50, 204,0.6);\r\n");
      out.write("        }\r\n");
      out.write("        div b{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            left:8%;\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("         .header #dd\r\n");
      out.write("        {\r\n");
      out.write("            font-size:large;\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            right:18%;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color:black;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #myChart,h2\r\n");
      out.write("        {\r\n");
      out.write("        \r\n");
      out.write("        animation-name:graph;\r\n");
      out.write("        animation-duration:4s;\r\n");
      out.write("        animation-iteration-count:1;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes graph\r\n");
      out.write("    {\r\n");
      out.write("        from{\r\n");
      out.write("            transform:rotateY(90deg);\r\n");
      out.write("        }\r\n");
      out.write("        to  \r\n");
      out.write("        {\r\n");
      out.write("            transform:rotateY(0deg);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    td{\r\n");
      out.write("    height:10px;\r\n");
      out.write("   background-color:none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("     button\r\n");
      out.write("      {\r\n");
      out.write("      height:35px;\r\n");
      out.write("      width:450px;\r\n");
      out.write("      background-color:blueviolet;\r\n");
      out.write("      color:white;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("      border-style:none;\r\n");
      out.write("      border-radius:10px;\r\n");
      out.write("      letter-spacing:2px;\r\n");
      out.write("      font-size:medium;\r\n");
      out.write("      font-weight:normal;\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      }\r\n");
      out.write("       button:hover{\r\n");
      out.write("                  background-color: rgba(153, 50, 204,0.8);\r\n");
      out.write("      \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("        <a href=\"index.jsp\"> <img src=\"media/expenses-removebg-preview (1).png\" style=\"height:47px;width:47px;padding:22px;margin-left:33px;\"> </a>    <b>Spring Expenses Tracker</b>\r\n");
      out.write("        <a href=\"home.jsp\" id=\"dd\"><i class=\"fa-solid fa-home\"></i>&nbsp;Home</a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
    
	 ExpenseService expenseService=new ExpenseServiceImpl();

    User user=(User) session.getAttribute("userInfo");
	System.out.println("print user details "+user);
    List<Expense> listOfExpense=expenseService.viewExpense(user.getUserId());

    System.out.println("GRAPHS "+listOfExpense);
   double utilitiesAmount=0.0;
   double transportAmount=0.0;
   double groceryAmount=0.0;
   double diningAmount=0.0;
   double entertaainmentAmount=0.0;
   double healthAmount=0.0;
   double educationAmount=0.0;
   double personalCareAmount=0.0;
   double clothingAmount=0.0;
   double HomeAmount=0.0;
   double giftsAmount=0.0;
   double savingsAmount=0.0;
   double taxAmount=0.0;
   double othersAmount=0.0;
   double totalAmount=0.0;
    for(Expense e:listOfExpense)
    {
    	totalAmount+=e.getAmount();
    	if(e.getCategory().equalsIgnoreCase("utilities"))
    	{
    		utilitiesAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("transportation"))
    	{
    		transportAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("groceries"))
    	{
    		groceryAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("DiningOut"))
    	{
    		diningAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Entertainment"))
    	{
    		entertaainmentAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("HealthCare"))
    	{
    		healthAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Education"))
    	{
    		educationAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("PersonalCare"))
    	{
    		personalCareAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Clothing"))
    	{
    		clothingAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Home&maintanence"))
    	{
    		HomeAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Gift&Donations"))
    	{
    		giftsAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Savings&Investments"))
    	{
    		savingsAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Tax"))
    	{
    		taxAmount+=e.getAmount();
    	}
    	else if(e.getCategory().equalsIgnoreCase("Others"))
    	{
    		othersAmount+=e.getAmount();
    	}
    	
    }
    
 
      out.write("\r\n");
      out.write(" <br><br>\r\n");
      out.write(" <a href=\"ViewExpenses\" style=\"position:absolute;top:14%;right:3%;\"><button style=\"width:90px;\">BACK</button></a>\r\n");
      out.write("     <canvas id=\"myChart\"   width=\"700\" height=\"200\"></canvas>\r\n");
      out.write(" <script>\r\n");
      out.write(" \r\n");
      out.write("var xValues = [\"utilities\", \"Transportation\", \"Groceries\", \"Dining Out\", \"Entertainment\",\"Health Care\",\"Education\",\"personal care\",\"Clothing\",\"Home Maintanence\",\"Gifts & Donations\",\"Savings &Investments\",\"Tax\",\"Others\"];\r\n");
      out.write("var yValues = [");
      out.print( utilitiesAmount);
      out.write(',');
      out.print(transportAmount);
      out.write(',');
      out.print( groceryAmount);
      out.write(',');
      out.print(diningAmount);
      out.write(',');
      out.print( entertaainmentAmount);
      out.write(',');
      out.print(healthAmount);
      out.write(',');
      out.print( educationAmount);
      out.write(',');
      out.print(personalCareAmount);
      out.write(',');
      out.print(clothingAmount);
      out.write(',');
      out.print(HomeAmount);
      out.write(',');
      out.print( giftsAmount);
      out.write(',');
      out.print(savingsAmount);
      out.write(',');
      out.print( taxAmount);
      out.write(',');
      out.print(othersAmount);
      out.write("];\r\n");
      out.write("//var barColors = [\"red\", \"green\",\"blue\",\"orange\",\"brown\"];\r\n");
      out.write("\r\n");
      out.write("new Chart(\"myChart\", {\r\n");
      out.write("  type: \"bar\",\r\n");
      out.write("  data: {\r\n");
      out.write("    labels: xValues,\r\n");
      out.write("    datasets: [{\r\n");
      out.write("      backgroundColor:'blueviolet',\r\n");
      out.write("     \r\n");
      out.write("      data: yValues\r\n");
      out.write("    }]\r\n");
      out.write("  },\r\n");
      out.write("  options: {\r\n");
      out.write("    legend: {display:false},\r\n");
      out.write("    title: {\r\n");
      out.write("      display: true,\r\n");
      out.write("      text: \"AMOUNT SPENT ON EACH CATEGORY TILL TODAY\",\r\n");
      out.write("    	  fontSize: 18, // Adjust the font size as needed\r\n");
      out.write("          fontColor: 'purple',\r\n");
      out.write("          wordSpacing:2\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<center>\r\n");
      out.write("<div id=\"vd\" style=\"z-index:19;border-style:solid;position:absolute;top:15%;left:26%;display:none;    background-color:white;\">\r\n");
      out.write("<table border=\"2\" style=\"height:130px;width:690px;\">\r\n");
      out.write("<tr><th colspan=\"3\" align=\"center\">  AMOUNT SPENT TILL DATE = &#8377; ");
      out.print(totalAmount );
      out.write("</th></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><th>SNO</th><th>CATEGORY</th> <th>AMOUNT</th></tr>\r\n");
      out.write("<tr><td>1</td><td>Utilities</td><td>&#8377;");
      out.print( utilitiesAmount);
      out.write(" </td></tr>\r\n");
      out.write("<tr><td>2</td><td>Transportation</td><td>&#8377; ");
      out.print(transportAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>3</td><td>Groceries</td><td>&#8377; ");
      out.print( groceryAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>4</td><td>Dining Out</td><td>&#8377;");
      out.print(diningAmount);
      out.write(" </td></tr>\r\n");
      out.write("<tr><td>5</td><td>Entertainment</td><td>&#8377; ");
      out.print( entertaainmentAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>6</td><td>Health Care</td><td>&#8377; ");
      out.print(healthAmount);
      out.write(" </td></tr>\r\n");
      out.write("<tr><td>7</td><td>Education</td><td>&#8377; ");
      out.print( educationAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>8</td><td>Personal Care</td><td>&#8377; ");
      out.print(personalCareAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>9</td><td>Clothing</td><td>&#8377; ");
      out.print(clothingAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>10</td><td>Home Maintanence</td><td>&#8377;");
      out.print(HomeAmount);
      out.write(" </td></tr>\r\n");
      out.write("<tr><td>11</td><td>Gifts & Donations</td><td>&#8377; ");
      out.print( giftsAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>12</td><td>Savings & Investments</td><td>&#8377; ");
      out.print(savingsAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>13</td><td>Taxes</td><td>&#8377; ");
      out.print( taxAmount);
      out.write("</td></tr>\r\n");
      out.write("<tr><td>14</td><td>Others</td><td>&#8377; ");
      out.print(othersAmount);
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<button id=\"close\" style=\"width:690px;align:center;height:29px;background-color:red;border-radius:0px;\" onclick=\"hide()\">  Close </button>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("    <br>\r\n");
      out.write("    <center>\r\n");
      out.write("    <h2 style=\"color:red;text-shadow:1px 1px white;letter-spacing:1px;word-spacing:2px;\">TOTAL AMOUNT SPENT TILL DATE = &#8377; ");
      out.print(totalAmount );
      out.write("</h2>\r\n");
      out.write("    <br>\r\n");
      out.write("    <button onclick=\"showDetails();\">VIEW AMOUNT SPENT ON EACH CATEGORY</button>\r\n");
      out.write("    </center>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function showDetails(){\r\n");
      out.write("    	var x=document.querySelector(\"#vd\");\r\n");
      out.write("    	var y=document.querySelector(\"#myChart\");\r\n");
      out.write("    	if(x.style.display=='none')\r\n");
      out.write("    		{\r\n");
      out.write("    		x.style.display=\"block\";\r\n");
      out.write("    		y.style.display=\"none\";\r\n");
      out.write("    		}\r\n");
      out.write("    	else\r\n");
      out.write("    		{\r\n");
      out.write("    		\r\n");
      out.write("    		x.style.display=\"none\";\r\n");
      out.write("    		y.style.display=\"block\";\r\n");
      out.write("\r\n");
      out.write("    		}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function hide()\r\n");
      out.write("    {\r\n");
      out.write("    	var x=document.querySelector(\"#vd\");\r\n");
      out.write("		x.style.display=\"none\";\r\n");
      out.write("    	var y=document.querySelector(\"#myChart\");\r\n");
      out.write("		y.style.display=\"block\";\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
