/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-06-04 09:34:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jsp.expensetracker.entity.User;
import com.jsp.expensetracker.service.*;

public final class contactus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.jsp.expensetracker.service");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Contact Us</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"media/expenses-removebg-preview (1).png\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/c51795afff.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    #ctf\r\n");
      out.write("    {\r\n");
      out.write("height:476px;\r\n");
      out.write("width:480px;\r\n");
      out.write("border-style:none;\r\n");
      out.write("background-image:linear-gradient(to top right,rgba(138, 43, 226,0.6),rgba(138, 43, 226,0.4),rgba(138, 43, 226,0.5),rgba(138,43,226,0.7));\r\n");
      out.write("margin-top:80px;\r\n");
      out.write("margin-left:127px;\r\n");
      out.write("border-top-style:solid;\r\n");
      out.write("border-left-style:solid;\r\n");
      out.write("border-top-color:blueviolet;\r\n");
      out.write("border-left-color:blueviolet;\r\n");
      out.write("border-width:9px;\r\n");
      out.write("z-index: 2;\r\n");
      out.write("animation-name: cform;\r\n");
      out.write("animation-duration: 5s;\r\n");
      out.write("animation-iteration-count: 1;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes cform\r\n");
      out.write("    {\r\n");
      out.write("        from{\r\n");
      out.write("            transform:rotateY(90deg);\r\n");
      out.write("        }\r\n");
      out.write("        to  \r\n");
      out.write("        {\r\n");
      out.write("            transform:rotateY(0deg);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    label\r\n");
      out.write("    {\r\n");
      out.write("        margin-left:75px;\r\n");
      out.write("        font-weight: bolder;\r\n");
      out.write("        letter-spacing:2px;\r\n");
      out.write("        font-size:18px;\r\n");
      out.write("        color:white;\r\n");
      out.write("        text-shadow:1px 1px blueviolet;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input{\r\n");
      out.write("\r\n");
      out.write("        border-style: none;\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        margin-left:56px;\r\n");
      out.write("        width:70%;\r\n");
      out.write("        height:39px;\r\n");
      out.write("        font-size:medium;\r\n");
      out.write("        color:blueviolet;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input:focus{\r\n");
      out.write("        width:72%;\r\n");
      out.write("    }\r\n");
      out.write("    textarea:focus{\r\n");
      out.write("        width:72%;\r\n");
      out.write("    }\r\n");
      out.write("    #cth\r\n");
      out.write("    {\r\n");
      out.write("        letter-spacing:3px;\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        color:white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        text-shadow:2px 2px grey;\r\n");
      out.write("        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;\r\n");
      out.write("    padding-top: 1px;\r\n");
      out.write("    }\r\n");
      out.write("    .buton\r\n");
      out.write("    {\r\n");
      out.write("        height:35px;\r\n");
      out.write("        width:20%;\r\n");
      out.write("        color:white;\r\n");
      out.write("        border-radius:20px;\r\n");
      out.write("        border-style:none;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    #sbm\r\n");
      out.write("    {\r\n");
      out.write("        background-color:blueviolet;\r\n");
      out.write("        margin-left:114px;\r\n");
      out.write("        font-size:20px;\r\n");
      out.write("        width:50%;\r\n");
      out.write("        height:40px;\r\n");
      out.write("        letter-spacing: 3px;\r\n");
      out.write("        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    #cont\r\n");
      out.write("    {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right:11%;\r\n");
      out.write("        top:26%;\r\n");
      out.write("    }\r\n");
      out.write("    *\r\n");
      out.write("        {\r\n");
      out.write("            margin:0%;\r\n");
      out.write("            padding:0%;\r\n");
      out.write("        }\r\n");
      out.write("        .header\r\n");
      out.write("        {\r\n");
      out.write("            margin:0px;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            height:90px;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background-color: rgba(153, 50, 204,0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div b{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            left:8%;\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         .header #dd\r\n");
      out.write("        {\r\n");
      out.write("            font-size:large;\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            right:18%;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color:black;\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
   
//User user=(User) session.getAttribute("userInfo");


User userInfo=(User)session.getAttribute("userInfo"); 
//System.out.println("checking in sending mail"+userInfo);
UserService userService=new UserServieImpl();
User user=userService.findUserById(userInfo.getUserId());
System.out.println(user+"checking");

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("        <a href=\"index.jsp\"> <img src=\"media/expenses-removebg-preview (1).png\" style=\"height:47px;width:47px;padding:22px;margin-left:33px;\"> </a>    <b>Spring Expenses Tracker</b>\r\n");
      out.write("        <a href=\"home.jsp\" id=\"dd\"><i class=\"fa-solid fa-home\"></i>&nbsp;Home</a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("<div id=\"ctf\"><br>\r\n");
      out.write("        <form method=\"post\" action=\"Contact\">\r\n");
      out.write("            <h3 id=\"cth\">CONTACT US</h3>\r\n");
      out.write("<br><br>\r\n");
      out.write("            <label for=\"uname\"><i class=\"fa-solid fa-user\"></i> USERNAME </label><br>\r\n");
      out.write("            <input type=\"text\"    required   id=\"uname\"  name=\"username\" autocomplete=\"off\" value=");
      out.print(user.getUsername() );
      out.write(" readonly><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"mail\"><i class=\"fa-solid fa-envelope\"></i> EMAIL</label><br>\r\n");
      out.write("            <input type=\"email\"    required   id=\"mail\"  name=\"email\" autocomplete=\"off\"  value=");
      out.print(user.getEmail() );
      out.write(" readonly><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <label for=\"comment\"><i class=\"fa-solid fa-comment\"></i> COMMENT</label><br>\r\n");
      out.write("            <textarea name=\"comment\" id=\"cmt\" required rows=\"7\"  style=\"margin-left:56px;border-style:none;width:70%;text-align: center;color:blueviolet;font-size: large;\" autofocus></textarea><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <input type=\"submit\" value=\"SUBMIT\" id=\"sbm\" class=\"buton\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <img src=\"media/contactus.png\" height=\"410px\" width=\"480px\" id=\"cont\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
