/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-06-04 09:34:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jsp.expensetracker.entity.User;

public final class KnowSavings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("            \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Know Savings</title>\r\n");
      out.write(" <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"media/expenses-removebg-preview (1).png\">\r\n");
      out.write("      <style>\r\n");
      out.write("      #myChart{\r\n");
      out.write("     position:absolute;\r\n");
      out.write("     top:29%;\r\n");
      out.write("    left:25%;\r\n");
      out.write("    \r\n");
      out.write("      }\r\n");
      out.write("      body{\r\n");
      out.write("      overflow:hidden;\r\n");
      out.write("      }\r\n");
      out.write("      #result{\r\n");
      out.write("      height:320px;\r\n");
      out.write("      width:520px;\r\n");
      out.write("      border-style:solid;\r\n");
      out.write("      position:absolute;\r\n");
      out.write("      top:33%;\r\n");
      out.write("      left:10%;\r\n");
      out.write("      font-size:17px;\r\n");
      out.write("      background-color:whitesmoke;\r\n");
      out.write("      animation-name: cfor;\r\n");
      out.write("animation-duration: 3s;\r\n");
      out.write("animation-iteration-count: 1;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes cfor\r\n");
      out.write("    {\r\n");
      out.write("        from{\r\n");
      out.write("            transform:rotateY(90deg);\r\n");
      out.write("        }\r\n");
      out.write("        to  \r\n");
      out.write("        {\r\n");
      out.write("            transform:rotateY(0deg);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("      a button\r\n");
      out.write("      {\r\n");
      out.write("      height:39px;\r\n");
      out.write("      width:150px;\r\n");
      out.write("      background-color:blueviolet;\r\n");
      out.write("      color:white;\r\n");
      out.write("      text-align:center;\r\n");
      out.write("      border-style:none;\r\n");
      out.write("      border-radius:10px;\r\n");
      out.write("      letter-spacing:2px;\r\n");
      out.write("      font-size:medium;\r\n");
      out.write("      font-weight:normal;\r\n");
      out.write("      box-shadow:2px 2px 2px 2px whitesmoke;\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      }\r\n");
      out.write("      a button:hover{\r\n");
      out.write("                  background-color: rgba(153, 50, 204,0.8);\r\n");
      out.write("      \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("       *\r\n");
      out.write("        {\r\n");
      out.write("            margin:0%;\r\n");
      out.write("            padding:0%;\r\n");
      out.write("        }\r\n");
      out.write("        .header\r\n");
      out.write("        {\r\n");
      out.write("            margin:0px;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            height:90px;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background-color: rgba(153, 50, 204,0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        div b{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            left:8%;\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("          .header #dd\r\n");
      out.write("        {\r\n");
      out.write("            font-size:large;\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            right:18%;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color:black;\r\n");
      out.write("        }\r\n");
      out.write("      \r\n");
      out.write("       .more h4{\r\n");
      out.write("       font-size:28px;\r\n");
      out.write("       z-index:5;\r\n");
      out.write("       }\r\n");
      out.write("      </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("        <a href=\"index.jsp\"> <img src=\"media/expenses-removebg-preview (1).png\" style=\"height:47px;width:47px;padding:22px;margin-left:33px;\"> </a>    <b>Spring Expenses Tracker</b>\r\n");
      out.write("        <a href=\"home.jsp\" id=\"dd\"><i class=\"fa-solid fa-home\"></i>&nbsp;Home</a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br><center><image src=\"media/datanf.gif\" height=\"250px\" width=\"250px\" id=\"ii\" style=\"display:none;\">\r\n");
      out.write("    </image>\r\n");

User user=(User) session.getAttribute("userInfo");
double salary=(Double)request.getAttribute("salary");
double expenses=(Double)request.getAttribute("total");
double savings=Math.ceil((Double)request.getAttribute("savings"));
String monthName=(String)request.getAttribute("monthName");

if( expenses!=0.0){

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"result\">\r\n");
      out.write("<img src=\"media/save.gif\" height=\"320px\" width=\"230px\" style=\"float:left;display:inline;\">\r\n");
      out.write("<div  style=\"padding:5px;margin-left:7px;color:blueviolet;text-align:center\"><br>\r\n");
      out.write("<h2 style=\"text-decoration:underline;text-shadow:1px 0px lightgrey;font-size:24px;letter-spacing:2px;word-spacing:3px;\">Your Savings</h2>\r\n");
      out.write("<br><h3>Month Name = &#128467; ");
      out.print(monthName );
      out.write("</h3>\r\n");
      out.write("<br>\r\n");
      out.write("<h3>Your Salary = &#8377; ");
      out.print(salary );
      out.write("</h3><br>\r\n");
      out.write("<h3> Your Expenses = &#8377;");
      out.print(expenses );
      out.write(" </h3><br>\r\n");
      out.write("<h3> Your Savings = &#8377;");
      out.print(salary-expenses );
      out.write(" </h3><br>\r\n");
      out.write("\r\n");
      out.write("<h3>Savings : ");
      out.print(savings );
      out.write(" %</h3><br>\r\n");
      out.write("<h3>Expenses : ");
      out.print(100-savings );
      out.write(" %</h3></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"chart\">\r\n");
      out.write("\r\n");
      out.write("<canvas id=\"myChart\" width=\"800\" height=\"190\"></canvas></div>\r\n");
      out.write(" <script>\r\n");
      out.write(" \r\n");
      out.write("var xValues=[\"EXPENSES = ");
      out.print(100-savings);
      out.write(" %\",\" SAVINGS = ");
      out.print(savings);
      out.write(" %\"];\r\n");
      out.write("var yValues=[");
      out.print(100-savings);
      out.write(',');
      out.print(savings);
      out.write("];\r\n");
      out.write("var barColors=[\"red\",\"blue\"];\r\n");
      out.write("new Chart(\"myChart\", {\r\n");
      out.write("  type: \"pie\",\r\n");
      out.write("  data: {\r\n");
      out.write("    labels: xValues,\r\n");
      out.write("    datasets: [{\r\n");
      out.write("      backgroundColor:barColors,\r\n");
      out.write("     \r\n");
      out.write("      data: yValues\r\n");
      out.write("    }]\r\n");
      out.write("  },\r\n");
      out.write("  options: {\r\n");
      out.write("    legend: {display:true},\r\n");
      out.write("    title: {\r\n");
      out.write("      display: true,\r\n");
      out.write("      text: \"Your Savings & Expenses In ");
      out.print(monthName);
      out.write("\",\r\n");
      out.write("    	  fontSize: 19, // Adjust the font size as needed\r\n");
      out.write("          fontColor: 'purple',\r\n");
      out.write("          wordSpacing:2\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<center>\r\n");
      out.write("<a href=\"Savings.jsp\" ><button style=\"position:absolute;top:15%;right:3%;\" id=\"bck\">&#10096; GO BACK</button></a></center>\r\n");
}else{ 
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.getElementById(\"ii\").style.display=\"block\";\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<center>\r\n");
      out.write("<h2>Hello ");
      out.print(user.getUsername() );
      out.write(" !! You Didn't Added Any Expenses In  ");
      out.print(monthName );
      out.write(" </h2><br>\r\n");
      out.write("<h2> <a href=\"ViewExpenses\" style=\"text-decoration:none;\">Click here to check all Your Expenses Details</a></h2>\r\n");
      out.write("<br><a href=\"Savings.jsp\" ><button  id=\"bck\">&#10096; GO BACK</button></a></center>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
} 
      out.write('\r');
      out.write('\n');
 if(expenses > salary) {
	
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    document.getElementById(\"myChart\").style.display=\"none\";\r\n");
      out.write("    document.getElementById(\"result\").style.display=\"none\";\r\n");
      out.write("    document.getElementById(\"bck\").style.display=\"none\";\r\n");
      out.write("   \r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("   <center >  <img src=\"media/flyMoney.gif\" height=\"500px\" width=\"1020px\" style=\"position:absolute;top:16%;left:17%;z-index:-1;opacity:0.4;\"><br> <center >\r\n");
      out.write("   <center >  <br><br><br><div class=\"more\" ><h4>Hello ");
      out.print(user.getUsername()  );
      out.write("!!! </h4><br>\r\n");
      out.write("    <h4>Your Salary in ");
      out.print(monthName );
      out.write("=&#8377; ");
      out.print(salary );
      out.write("</h4><br>\r\n");
      out.write("    <h4>Your Expenses in ");
      out.print(monthName );
      out.write("= &#8377; ");
      out.print(expenses );
      out.write("</h4><br>\r\n");
      out.write("    <h4 style=\"color:purple;\">You spent more than you earned in ");
      out.print(monthName );
      out.write("</h4><br>\r\n");
      out.write("    <h4 id=\"svn\"> Your Savings is ");
      out.print(savings );
      out.write("</h4>\r\n");
      out.write("    \r\n");
      out.write("    <h4>We are suggesting some financial precautions to u <a href=\"media/financialprecautionset.pdf\" target=\"blank\">Click here</a></h4>\r\n");
      out.write("    <br><a href=\"Savings.jsp\" ><button  >&#10096; GO BACK</button></a>\r\n");
      out.write("    </center>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
