/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-06-04 09:42:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/c51795afff.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <link rel=\"icon\" href=\"media/expenses-removebg-preview (1).png\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("  <a href=\"index.jsp\"> <img src=\"media/expenses-removebg-preview (1).png\" style=\"height:47px;width:47px;padding:22px;margin-left:33px;\"> </a>    <b>Spring Expenses Tracker</b>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"dd\">\r\n");
      out.write("        <center>\r\n");
      out.write("            <br>\r\n");
      out.write("        <div class=\"frm\">\r\n");
      out.write("            <center>    <h2 id=\"para\">Sign In With</h2></center>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mainfrm\">\r\n");
      out.write("<br>\r\n");
      out.write("                <button style=\"background-color: rgba(61, 64, 139,0.9);\"><a href=\"https://www.facebook.com/\" style=\"color:white;\"><img src=\"media/facebook-removebg-preview.png \"  height=\"14px\" width=\"14px\" >  &nbsp; Facebook</a></button>&nbsp;&nbsp; &nbsp;&nbsp;                <button id=\"gb\"><a href=\"https://www.google.co.in/\"><img src=\"media/search-removebg-preview.png\" height=\"14px\" width=\"14px\">&nbsp;Google</a></button>\r\n");
      out.write("            \r\n");
      out.write("<br><br>\r\n");
      out.write("<br>\r\n");
      out.write("<form method=\"post\" action=\"Login\">\r\n");
      out.write("     <label for=\"username\" ><i class=\"fa-solid fa-user\"></i> username</label><br>\r\n");
      out.write("     <input type=\"text\" required id=\"username\" autocomplete=\"off\" name=\"username\">\r\n");
      out.write("<br><br>\r\n");
      out.write("<label for=\"password\" style=\"margin-right: 170px;\"><i class=\"fa-solid fa-key\"></i> password &nbsp;&nbsp;&nbsp;<a href=\"forgotpassword.jsp\">Forgot?</a></label><br>\r\n");
      out.write("<input type=\"password\" required id=\"password\" autocomplete=\"off\" name=\"password\">\r\n");
      out.write("<br><br>\r\n");
      out.write("<input type=\"submit\" value=\"Sign in\" id=\"bt\">\r\n");
      out.write("</form><br>\r\n");

String message=(String) request.getAttribute("msg");
if(message !=null)
{

      out.write("\r\n");
      out.write("<h4>");
      out.print( message );
      out.write("</h4>\r\n");
      out.write("<script>alert('");
      out.print( message );
      out.write("');</script>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
}

      out.write("\r\n");
      out.write("Not a memeber?&nbsp;&nbsp;<a href=\"register.jsp\" target=\"_blank\">Signup now</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </center>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

   String m=(String) request.getAttribute("signup_msg");
    if(m!=null){
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    alert('");
      out.print( m );
      out.write("')\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");

   String lomsg= (String) request.getAttribute("logout");
    if(lomsg!=null){
    
      out.write("\r\n");
      out.write("    <script>alert('");
      out.print(lomsg);
      out.write("')</script>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
