/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-06-04 09:37:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/c51795afff.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <link rel=\"icon\" href=\"../media/expenses-removebg-preview (1).png\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("   *\r\n");
      out.write("        {\r\n");
      out.write("            margin:0%;\r\n");
      out.write("            padding:0%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("         .header\r\n");
      out.write("        {\r\n");
      out.write("            margin:0px;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            height:90px;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background-color: rgba(153, 50, 204,0.6);\r\n");
      out.write("        }\r\n");
      out.write("        #ddi\r\n");
      out.write("        {\r\n");
      out.write("            margin-top:19px;\r\n");
      out.write("        height:589px;\r\n");
      out.write("        width:740px;\r\n");
      out.write("        background-color:rgb(70, 0, 211);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        div\r\n");
      out.write("        {\r\n");
      out.write("            margin-top:30px;\r\n");
      out.write("        height:640px;\r\n");
      out.write("        width:740px;\r\n");
      out.write("        background-color:rgb(70, 0, 211);\r\n");
      out.write("        }\r\n");
      out.write("        div b{\r\n");
      out.write("            font-size: 27px;\r\n");
      out.write("            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        div input\r\n");
      out.write("        {\r\n");
      out.write("            height:54px;\r\n");
      out.write("            width:686px;\r\n");
      out.write("            padding-left:15px;\r\n");
      out.write("            border-style:none;\r\n");
      out.write("            border-radius:2px;\r\n");
      out.write("        }\r\n");
      out.write("         #bb{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            left:8%;\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        #btt\r\n");
      out.write("        {\r\n");
      out.write("            height:48px;\r\n");
      out.write("            width:703px;\r\n");
      out.write("            border-radius:2px;\r\n");
      out.write("            background-color: rgba(0, 128, 0,0.9);\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"header\">\r\n");
      out.write("     <a href=\"index.jsp\">   <img src=\"media/expenses-removebg-preview (1).png\" style=\"height:47px;width:47px;padding:22px;margin-left:33px;\"></a>     <b id=\"bb\">Spring Expenses Tracker</b>\r\n");
      out.write("         </div>\r\n");
      out.write(" <center>\r\n");
      out.write("        <div id=\"ddi\">\r\n");
      out.write("            <br>\r\n");
      out.write("            <b style=\"color:white;letter-spacing: 2px;\">CREATE ACCOUNT</b>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <form method=\"post\" action=\"Registration\">\r\n");
      out.write("                <input type=\"text\" required placeholder=\"Your Name\" autocomplete=\"off\" name=\"fullname\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <input type=\"text\" required placeholder=\"Your Username\" autocomplete=\"off\" name=\"username\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <input type=\"email\" required placeholder=\"Your Email\" autocomplete=\"off\" name=\"email\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <input type=\"tel\" required placeholder=\"Your Mobile\" autocomplete=\"off\" name=\"mobile\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <input type=\"password\" required placeholder=\"Password\" autocomplete=\"off\" name=\"password\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <input type=\"password\" required placeholder=\"Rematch Your Password\" autocomplete=\"off\" name=\"cpassword\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <input type=\"submit\" required value=\"SIGN UP\" id=\"btt\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <span style=\"color:white;\">Already have an account? </span>&nbsp;<a href=\"login.jsp\" style=\"color:white;\">Login now</a>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </center>\r\n");
      out.write("    \r\n");
      out.write("    ");

String message=(String) request.getAttribute("msg");
if(message !=null)
{

      out.write("\r\n");
      out.write("<script>alert('");
      out.print( message );
      out.write(" Create an account now !!');</script>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");

   String m=(String) request.getAttribute("signup_ms");
    if(m!=null){
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    alert('");
      out.print( m );
      out.write("')\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
