/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-06-04 09:35:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;
import java.sql.Date;
import java.util.*;
import com.jsp.expensetracker.entity.Expense;
import com.jsp.expensetracker.entity.User;
import com.jsp.expensetracker.service.*;

public final class ThisWeekExpenses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.jsp.expensetracker.service");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.Expense");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.User");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("                \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>THIS WEEK EXPENSES</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/c51795afff.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"media/expenses-removebg-preview (1).png\">\r\n");
      out.write("    <style>\r\n");
      out.write("      body\r\n");
      out.write("        {\r\n");
      out.write("            background-image: url(media/bg.png);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-size:cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		*\r\n");
      out.write("        {\r\n");
      out.write("            margin:0%;\r\n");
      out.write("            padding:0%;\r\n");
      out.write("        }\r\n");
      out.write("        .header\r\n");
      out.write("        {\r\n");
      out.write("            margin:0px;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            height:90px;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background-color: rgba(153, 50, 204,0.6);\r\n");
      out.write("        }\r\n");
      out.write("        div b{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            left:8%;\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("         .header #dd\r\n");
      out.write("        {\r\n");
      out.write("            font-size:large;\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            right:18%;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color:black;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        td,th{\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        height:30px;\r\n");
      out.write("        border-style:solid;\r\n");
      out.write("        border-color:lightgrey;\r\n");
      out.write("        width:180px;\r\n");
      out.write("        }\r\n");
      out.write("        th\r\n");
      out.write("        {\r\n");
      out.write("        color:blueviolet;\r\n");
      out.write("        }\r\n");
      out.write("       table{\r\n");
      out.write("       margin-top:70px;\r\n");
      out.write("       height:190px;\r\n");
      out.write("       background-color:white;\r\n");
      out.write("       }\r\n");
      out.write("       </style> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("        <a href=\"index.jsp\"> <img src=\"media/expenses-removebg-preview (1).png\" style=\"height:47px;width:47px;padding:22px;margin-left:33px;\"> </a>    <b>Spring Expenses Tracker</b>\r\n");
      out.write("        <a href=\"home.jsp\" id=\"dd\"><i class=\"fa-solid fa-home\"></i>&nbsp;Home</a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");

LocalDate currentDate = LocalDate.now();

    Date d7=Date.valueOf(currentDate );
	Date d6=Date.valueOf(currentDate.minusDays(1));
	Date d5=Date.valueOf(currentDate.minusDays(2));
	Date d4=Date.valueOf(currentDate.minusDays(3));
	Date d3=Date.valueOf(currentDate.minusDays(4));
	Date d2=Date.valueOf(currentDate.minusDays(5));
	Date d1=Date.valueOf(currentDate.minusDays(6));

ExpenseService expenseService=new ExpenseServiceImpl();
double d7Total=0;
double d6Total=0;
double d5Total=0;
double d4Total=0;
double d3Total=0;
double d2Total=0;
double d1Total=0;

User user=(User) session.getAttribute("userInfo");
System.out.println("printing user details "+user);
List<Expense> listOfExpense=expenseService.viewExpense(user.getUserId());
if(listOfExpense!=null){
for(Expense l:listOfExpense)
{
	if(l.getDate().equals(d7)){
		d7Total+=l.getAmount();
	}
	else if(l.getDate().equals(d6)){
		d6Total+=l.getAmount();
	}
	else if(l.getDate().equals(d5)){
		d5Total+=l.getAmount();
	}
	else if(l.getDate().equals(d4)){
		d4Total+=l.getAmount();
	}
	else if(l.getDate().equals(d3)){
		d3Total+=l.getAmount();
	}
	else if(l.getDate().equals(d2)){
		d2Total+=l.getAmount();
	}
	else if(l.getDate().equals(d1)){
		d1Total+=l.getAmount();
	}
}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("<canvas id=\"myChart\" style=\"width:100%;max-width:900px;height:500px;margin-left:30px;margin-right:60px;float:left;\"></canvas>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("const xValues = ['");
      out.print(d1);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(d2);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(d3);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(d4);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(d5);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(d6);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(d7);
      out.write("'];\r\n");
      out.write("\r\n");
      out.write("const yValues = [");
      out.print(d1Total);
      out.write(',');
      out.print(d2Total);
      out.write(',');
      out.print(d3Total);
      out.write(',');
      out.print(d4Total);
      out.write(',');
      out.print(d5Total);
      out.write(',');
      out.print(d6Total);
      out.write(',');
      out.print(d7Total);
      out.write("];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("new Chart(\"myChart\", {\r\n");
      out.write("  type: \"line\",\r\n");
      out.write("  data: {\r\n");
      out.write("    labels: xValues,\r\n");
      out.write("    datasets: [{\r\n");
      out.write("      fill: false,\r\n");
      out.write("      lineTension: 0,\r\n");
      out.write("      backgroundColor: \"rgba(0,0,255,1.0)\",\r\n");
      out.write("      borderColor: \"rgba(0,0,255,0.7)\",\r\n");
      out.write("      data: yValues\r\n");
      out.write("    }]\r\n");
      out.write("  },\r\n");
      out.write("  options: {\r\n");
      out.write("    legend: {display: false},\r\n");
      out.write("    title: {\r\n");
      out.write("        display: true,\r\n");
      out.write("        text: \"YOUR EXPENSES IN THIS WEEK\",\r\n");
      out.write("      	  fontSize: 18, // Adjust the font size as needed\r\n");
      out.write("            fontColor: 'purple',\r\n");
      out.write("            wordSpacing:2\r\n");
      out.write("      }\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" id=\"tb\">\r\n");
      out.write("<tr><th colspan=\"2\"><b>");
      out.print(user.getUsername() );
      out.write(" EXPENSES IN THIS WEEK</b></th></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>DATE</th>\r\n");
      out.write("<th>AMOUNT SPENT</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(d1 );
      out.write("</td>\r\n");
      out.write("<td>&#8377; ");
      out.print(d1Total );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(d2 );
      out.write("</td>\r\n");
      out.write("<td>&#8377; ");
      out.print(d2Total );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(d3 );
      out.write("</td>\r\n");
      out.write("<td>&#8377; ");
      out.print(d3Total );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(d4 );
      out.write("</td>\r\n");
      out.write("<td>&#8377; ");
      out.print(d4Total );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(d5 );
      out.write("</td>\r\n");
      out.write("<td>&#8377; ");
      out.print(d5Total );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(d6 );
      out.write("</td>\r\n");
      out.write("<td>&#8377; ");
      out.print(d6Total );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(d7 );
      out.write("</td>\r\n");
      out.write("<td>&#8377; ");
      out.print(d7Total );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"2\" style=\"color:blueviolet;\"><b>AMOUNT SPENT IN THIS WEEK Rs ");
      out.print(d1Total+d2Total+d3Total+d4Total+d5Total+d6Total+d7Total );
      out.write("/-</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");

if(d1Total==0.0 && d2Total==0.0 && d3Total==0.0 && d4Total==0.0 && d5Total==0.0 && d6Total==0.0 && d7Total==0.0)
	
{

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.querySelector(\"#myChart\").style.display=\"none\";\r\n");
      out.write("document.querySelector(\"#tb\").style.display=\"none\";\r\n");
      out.write("</script>\r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write("<center><h2>Hello ");
      out.print(user.getUsername() );
      out.write("!!</h2></center><br><br>\r\n");
      out.write("<center><h2>YOU DIDNOT ADDED ANY EXPENSES IN THIS WEEK</h2></center>\r\n");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
