/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-06-04 09:34:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.jsp.expensetracker.entity.Expense;
import com.jsp.expensetracker.entity.User;

public final class viewtotalexpense_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.Expense");
    _jspx_imports_classes.add("com.jsp.expensetracker.entity.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>View Total Expenses</title>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/c51795afff.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"icon\" href=\"media/expenses-removebg-preview (1).png\">\r\n");
      out.write("<style>\r\n");
      out.write("table\r\n");
      out.write("{\r\n");
      out.write("margin-top:90px;\r\n");
      out.write("background-color:bisque;\r\n");
      out.write("border-style:none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".ro:hover\r\n");
      out.write("{\r\n");
      out.write("background-color:lightgrey;\r\n");
      out.write("}\r\n");
      out.write("td\r\n");
      out.write("{\r\n");
      out.write("text-align:center;\r\n");
      out.write("background-color:white;\r\n");
      out.write("border-color:lightgrey;\r\n");
      out.write("padding:10px;\r\n");
      out.write("border-top-color:rgba(153, 50, 204,0.6);\r\n");
      out.write("border-bottom-color:rgba(153, 50, 204,0.6);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("     body\r\n");
      out.write("        {\r\n");
      out.write("            background-image: url(media/bg.png);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-size:cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		*\r\n");
      out.write("        {\r\n");
      out.write("            margin:0%;\r\n");
      out.write("            padding:0%;\r\n");
      out.write("        }\r\n");
      out.write("        .header\r\n");
      out.write("        {\r\n");
      out.write("            margin:0px;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            height:90px;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            background-color: rgba(153, 50, 204,0.6);\r\n");
      out.write("        }\r\n");
      out.write("        div b{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            left:8%;\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("         .header #dd\r\n");
      out.write("        {\r\n");
      out.write("            font-size:large;\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            right:18%;\r\n");
      out.write("            top:5%;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color:black;\r\n");
      out.write("        }\r\n");
      out.write("        button\r\n");
      out.write("        {\r\n");
      out.write("        	border-style:none;\r\n");
      out.write("        	color:white;\r\n");
      out.write("        	height:30px;\r\n");
      out.write("        	width:90px;\r\n");
      out.write("        	border-radius:20px;\r\n");
      out.write("        	font-size:15px;\r\n");
      out.write("        	\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #ima\r\n");
      out.write("        {\r\n");
      out.write("        	height:200px;\r\n");
      out.write("        	width:300px;\r\n");
      out.write("        	margin-top:100px;\r\n");
      out.write("        	display:none;\r\n");
      out.write("        	\r\n");
      out.write("        }\r\n");
      out.write("        #meg,#mega,#meeg\r\n");
      out.write("        {\r\n");
      out.write("        	margin-top:20px;\r\n");
      out.write("        	display:none;\r\n");
      out.write("        	color:gray;\r\n");
      out.write("        	display:none;\r\n");
      out.write("        }\r\n");
      out.write("        #bck\r\n");
      out.write("        {\r\n");
      out.write("        	height:40px;\r\n");
      out.write("        	width:300px;\r\n");
      out.write("        	background-color:rgba(0,0,255,0.8);\r\n");
      out.write("        	color:white;\r\n");
      out.write("        	border-radius:20px;\r\n");
      out.write("        	font-size:medium;\r\n");
      out.write("        	font-weight:bold;\r\n");
      out.write("        	letter-spacing:1px;\r\n");
      out.write("        	\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #bck:hover\r\n");
      out.write("        {\r\n");
      out.write("        		width:340px;\r\n");
      out.write("        		background-color:blue;\r\n");
      out.write("        		box-shadow:3px 3px 2px 2px white; \r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("        <a href=\"index.jsp\"> <img src=\"media/expenses-removebg-preview (1).png\" style=\"height:47px;width:47px;padding:22px;margin-left:33px;\"> </a>    <b>Spring Expenses Tracker</b>\r\n");
      out.write("        <a href=\"home.jsp\" id=\"dd\"><i class=\"fa-solid fa-home\"></i>&nbsp;Home</a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
    User user=(User) session.getAttribute("userInfo");
 
      out.write("\r\n");
      out.write("<center>\r\n");

 String popup=  (String) request.getAttribute("processMsg");
    Double result=(Double)request.getAttribute("result");
    if(popup!=null  && result!=null){
    
      out.write("\r\n");
      out.write("    <script>alert('CALUCLATION IN PROGRES !!');\r\n");
      out.write("</script>    \r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");
 
  Date startDate=(Date) request.getAttribute("startdate");
Date endDate=(Date) request.getAttribute("enddate");

      out.write("\r\n");
      out.write("<button style=\"height:37px;width:85px;border-style:none;border-radius:8px;background-color:black;position:absolute;right:3%;top:15%;\"><a href=\"totalexpenses.jsp\" style=\"text-decoration:none;color:white;letter-spacing:1px;\"><i class=\"fa-solid fa-backward fa-beat-fade\"></i> BACK</a></button>\r\n");
      out.write("<img src=\"media/empty.png\" id=\"ima\">\r\n");
      out.write("<h2 id=\"meg\">Hello ");
      out.print(user.getUsername() );
      out.write(" , It seems that you don't have added any expense details between given dates</h2>\r\n");
      out.write("<h4 id=\"mega\" style=\"padding:8px;\">CLICK BELOW BUTTON TO ADD ANY EXPENSE DETAILS</h4>\r\n");
      out.write("<button style=\"color:white;background-color:rgba(0,0,255,0.6);height:38px;width:210px;\" id=\"meeg\"><a href=\"addexpenses.jsp\" style=\"text-decoration:none;color:white;\">+ ADD EXPENSE DETAILS</a></button>\r\n");
      out.write("\r\n");
      out.write("<table border=\"2px\"  width=\"1100px\"  cellspacing=\"3px\" id=\"tbl\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr style=\"background-color:rgba(153, 50, 204,0.6);align:center;color:white;letter-spacing:1px;font-size:20px;\"   height=\"40px\" ><th colspan=\"6\"><b>");
      out.print( user.getUsername() );
      out.write(" Expenses Details</b></th></tr>\r\n");
      out.write("<tr style=\"background-color:rgba(153, 50, 204,0.6);align:center;color:white;letter-spacing:1px;font-size:20px;\"   height=\"40px\">\r\n");
      out.write("\r\n");
      out.write("<th colspan=\"6\" align=\"center\">START DATE : ");
      out.print(startDate );
      out.write("		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;   END DATE : ");
      out.print(endDate );
      out.write("</th>			\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr style=\"background-color:rgba(153, 50, 204,0.6);align:center;color:white;letter-spacing:1px;font-size:20px;\"   height=\"40px\">\r\n");
      out.write("<th>SNO</th>\r\n");
      out.write("<th>DATE</th>\r\n");
      out.write("<th>AMOUNT</th>\r\n");
      out.write("<th>CATEGORY</th>\r\n");
      out.write("<th>DESCRIPTION</th>\r\n");
      out.write("<th>ACTION</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("\r\n");
      out.write("<tbody>\r\n");



System.out.println("sd"+startDate);
System.out.println("ed"+endDate);
	int count=0;
	List<Expense> listOfExpenses=(List)request.getAttribute("list");
System.out.println("vte "+listOfExpenses);
	if(listOfExpenses  !=null){
		int n=0;
		for(Expense e:listOfExpenses ){
			System.out.println(e.getDate());
			if(e.getDate().after(startDate) && e.getDate().before(endDate) ){
			count++;

      out.write("\r\n");
      out.write("<tr >\r\n");
      out.write("<td class=\"ro\"><b>");
      out.print( ++n );
      out.write("</b></td>\r\n");
      out.write("<td class=\"ro\"><i>");
      out.print(e.getDate() );
      out.write("</i></td>\r\n");
      out.write("<td class=\"ro\"><b>&#8377; ");
      out.print(e.getAmount() );
      out.write("</b></td>\r\n");
      out.write("<td class=\"ro\">");
      out.print(e.getCategory() );
      out.write("</td>\r\n");
      out.write("<td class=\"ro\">");
      out.print(e.getDescription() );
      out.write("</td>\r\n");
      out.write("<td ><center><button type=\"submit\"  class=\"ud\"  style=\"background-color:rgba(0,0,255,0.7);\"><i class=\"fa-solid fa-pencil \"></i> <a href=\"UpdateExpense.jsp?expenseId=");
      out.print(e.getExpenseId() );
      out.write("\" style=\"text-decoration:none;color:white;\">Update</a> </button>\r\n");
      out.write(" &nbsp; &nbsp;&nbsp;<form method=\"post\" action=\"DeleteExpense\" style=\"display:inline;\"><input value=");
      out.print(e.getExpenseId());
      out.write(" hidden=true   name=\"exId\"><button type=\"submit\" class=\"de\" style=\"background-color:rgba(255,0,0,0.7);\"><i class=\"fa-solid fa-trash\"></i> Delete</button></form></center></td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");

			}	}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
if (result!=null ){ 
      out.write("\r\n");
      out.write("  <tr><td colspan=\"6\">  <b id=\"output\" style=\"color:blue;font-size:21px;\">");
      out.print(popup);
      out.print(result );
      out.write("</b></td></tr>\r\n");
      out.write("  ");
} 
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
	if(count==0) {
      out.write("\r\n");
      out.write("	\r\n");
      out.write(" <script>\r\n");
      out.write(" document.getElementById(\"tbl\").style.display=\"none\";\r\n");
      out.write(" document.getElementById(\"ima\").style.display=\"block\";\r\n");
      out.write(" document.getElementById(\"meg\").style.display=\"block\";\r\n");
      out.write(" document.getElementById(\"mega\").style.display=\"block\";\r\n");
      out.write(" document.getElementById(\"meeg\").style.display=\"block\";\r\n");
      out.write("	document.getElementById(\"output\").style.display=\"none\";\r\n");
      out.write(" </script>\r\n");
      out.write("</center>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><center><button id=\"bck\"><a href=\"ViewExpenses\" style=\"text-decoration:none;color:white;\"><i class=\"fa fa-solid fa-eye\" type=\"button\"></i> VIEW ALL EXPENSES</a></button></center><br><br><br>\r\n");
      out.write("\r\n");

	String alm=	(String) request.getAttribute("mess");
if(alm!=null){

      out.write("\r\n");
      out.write("<script>alert('");
      out.print(alm);
      out.write("')\r\n");
      out.write("window.location.href=\"TotalExpenses\";</script>\r\n");


} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
